-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-30 15:21:59 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Capture run of script in file called oo_schema_output.txt
set echo on
SPOOL oo_schema_output.txt

--student id: 35512075
--student name: Shamle Thilaksiri

DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY_DETAILS CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE JOURNEY CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     add_street   VARCHAR2 (50)  NOT NULL , 
     add_town     VARCHAR2 (50)  NOT NULL , 
     add_postcode NUMBER (7)  NOT NULL , 
     add_country  VARCHAR2 (50)  NOT NULL , 
     address_id   NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.add_street IS 'street address' 
;

COMMENT ON COLUMN ADDRESS.add_town IS 'town address' 
;

COMMENT ON COLUMN ADDRESS.add_postcode IS 'postcode address with size of 7' 
;

COMMENT ON COLUMN ADDRESS.add_country IS 'residing country ' 
;

COMMENT ON COLUMN ADDRESS.address_id IS 'address id - surrogate key' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( address_id ) ;

CREATE TABLE CABIN 
    ( 
     cabin_id        NUMBER (7)  NOT NULL , 
     cabin_sleep_cap NUMBER (5)  NOT NULL , 
     cabin_class     CHAR (3)  NOT NULL , 
     ship_id         NUMBER (7)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabinclass 
    CHECK (cabin_class IN ('BAL', 'INT', 'OCV', 'SUT')) 
;

COMMENT ON COLUMN CABIN.cabin_id IS 'cabin number' 
;

COMMENT ON COLUMN CABIN.cabin_sleep_cap IS 'sleep cabin capacity' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Lookup table values have been added : INT - Interior, OCV - Ocean view,BAL -  Balcony, SUT -  Suite ' 
;

COMMENT ON COLUMN CABIN.ship_id IS 'ship number' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_id, ship_id ) ;

CREATE TABLE COUNTRY_DETAILS 
    ( 
     country_code NUMBER (7)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY_DETAILS.country_code IS 'country code' 
;

COMMENT ON COLUMN COUNTRY_DETAILS.country_name IS 'country name' 
;

ALTER TABLE COUNTRY_DETAILS 
    ADD CONSTRAINT COUNTRY_DETAILS_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id            NUMBER (7)  NOT NULL , 
     cruise_name          VARCHAR2 (50)  NOT NULL , 
     cost_pp              NUMBER (11,2)  NOT NULL , 
     cruise_desc          VARCHAR2 (900)  NOT NULL , 
     cruise_dep_date_time DATE  NOT NULL , 
     ship_id              NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'cruise name' 
;

COMMENT ON COLUMN CRUISE.cost_pp IS 'cost per person' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'cruise description' 
;

COMMENT ON COLUMN CRUISE.cruise_dep_date_time IS 'date and time of cruise depature' 
;

COMMENT ON COLUMN CRUISE.ship_id IS 'ship number' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_REPORT_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE JOURNEY 
    ( 
     cruise_id        NUMBER (7)  NOT NULL , 
     port_code        NUMBER (7)  NOT NULL , 
     depature_arrival CHAR (3)  NOT NULL 
    ) 
;

ALTER TABLE JOURNEY 
    ADD 
    CHECK (depature_arrival IN ('ARR', 'DEP')) 
;

COMMENT ON COLUMN JOURNEY.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN JOURNEY.port_code IS 'port code' 
;

COMMENT ON COLUMN JOURNEY.depature_arrival IS 'Created lookup table for depature - DEP and arrival - ARR' 
;

ALTER TABLE JOURNEY 
    ADD CONSTRAINT JOURNEY_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE MANIFEST 
    ( 
     cruise_id                 NUMBER (7)  NOT NULL , 
     cabin_id                  NUMBER (7)  NOT NULL , 
     ship_id                   NUMBER (7)  NOT NULL , 
     passenger_id              NUMBER (7)  NOT NULL , 
     passenger_board_date_time DATE 
    ) 
;

COMMENT ON COLUMN MANIFEST.cruise_id IS 'cruise id' 
;

COMMENT ON COLUMN MANIFEST.cabin_id IS 'cabin number' 
;

COMMENT ON COLUMN MANIFEST.ship_id IS 'ship number' 
;

COMMENT ON COLUMN MANIFEST.passenger_id IS 'passenger number' 
;

COMMENT ON COLUMN MANIFEST.passenger_board_date_time IS 'passenger board date and time' 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT MANIFEST_PK PRIMARY KEY ( cruise_id, passenger_id ) ;

CREATE TABLE OPERATOR 
    ( 
     oper_id       NUMBER (7)  NOT NULL , 
     oper_name     VARCHAR2 (50)  NOT NULL , 
     oper_ceo_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.oper_id IS 'operator number' 
;

COMMENT ON COLUMN OPERATOR.oper_name IS 'operator name' 
;

COMMENT ON COLUMN OPERATOR.oper_ceo_name IS 'operator ceo name' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( oper_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id     NUMBER (7)  NOT NULL , 
     passenger_fname  VARCHAR2 (50)  NOT NULL , 
     passenger_lname  VARCHAR2 (50)  NOT NULL , 
     passenger_dob    DATE  NOT NULL , 
     passenger_gender CHAR (1)  NOT NULL , 
     guardian_id      NUMBER (7)  NOT NULL , 
     address_id       NUMBER (7)  NOT NULL , 
     phone_num        VARCHAR2 (20) 
    ) 
;

ALTER TABLE PASSENGER 
    ADD 
    CHECK (passenger_gender IN ('F', 'M')) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'passenger number' 
;

COMMENT ON COLUMN PASSENGER.passenger_fname IS 'passenger first name' 
;

COMMENT ON COLUMN PASSENGER.passenger_lname IS 'passenger last name' 
;

COMMENT ON COLUMN PASSENGER.passenger_dob IS 'passenger date of birth' 
;

COMMENT ON COLUMN PASSENGER.passenger_gender IS 'passenger gender' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'passenger number' 
;

COMMENT ON COLUMN PASSENGER.address_id IS 'address id - surrogate key' 
;

COMMENT ON COLUMN PASSENGER.phone_num IS 'phone number' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PORT 
    ( 
     port_code    NUMBER (7)  NOT NULL , 
     port_name    VARCHAR2 (50)  NOT NULL , 
     port_lat     NUMBER (9,6)  NOT NULL , 
     port_longt   NUMBER (9,6)  NOT NULL , 
     country_code NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'port code' 
;

COMMENT ON COLUMN PORT.port_name IS 'port name' 
;

COMMENT ON COLUMN PORT.port_lat IS 'port lattitude' 
;

COMMENT ON COLUMN PORT.port_longt IS 'port longtitude' 
;

COMMENT ON COLUMN PORT.country_code IS 'country code' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_id                 NUMBER (7)  NOT NULL , 
     ship_name               VARCHAR2 (50)  NOT NULL , 
     ship_commission_date    VARCHAR2 (50)  NOT NULL , 
     ship_tonnage            NUMBER (4,2)  NOT NULL , 
     ship_max_guest_capacity NUMBER (6)  NOT NULL , 
     ship_registered_country VARCHAR2 (50)  NOT NULL , 
     oper_id                 NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_id IS 'ship number' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'ship name' 
;

COMMENT ON COLUMN SHIP.ship_commission_date IS 'ship commission date' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'ship tonnage - maximum weight it can carry' 
;

COMMENT ON COLUMN SHIP.ship_max_guest_capacity IS 'maximum guest capacity' 
;

COMMENT ON COLUMN SHIP.ship_registered_country IS 'ship registered country' 
;

COMMENT ON COLUMN SHIP.oper_id IS 'operator number' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_id ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT fk_address_id FOREIGN KEY 
    ( 
     address_id
    ) 
    REFERENCES ADDRESS 
    ( 
     address_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT fk_cabin_manifest FOREIGN KEY 
    ( 
     cabin_id,
     ship_id
    ) 
    REFERENCES CABIN 
    ( 
     cabin_id,
     ship_id
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT fk_countrydetails_port FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY_DETAILS 
    ( 
     country_code
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT fk_cruise_id FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE JOURNEY 
    ADD CONSTRAINT fk_cruiseid_depdatetime FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST 
    ADD CONSTRAINT fk_passenger_id FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE JOURNEY 
    ADD CONSTRAINT fk_port_journey FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT fk_ship_cabin FOREIGN KEY 
    ( 
     ship_id
    ) 
    REFERENCES SHIP 
    ( 
     ship_id
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT fk_ship_cruise FOREIGN KEY 
    ( 
     ship_id
    ) 
    REFERENCES SHIP 
    ( 
     ship_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT fk_ship_operator FOREIGN KEY 
    ( 
     oper_id
    ) 
    REFERENCES OPERATOR 
    ( 
     oper_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT guardian_minor FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

SPOOL off
set echo off


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
