#include <iostream>
#include <cstdlib>

//This game takes into account the number of tries each player gets as input and in each chance they have to guess the number that is randomly generated by seeding the number generated. 

using namespace std;
int main() {

    //Seed the number generator
    srand(static_cast<unsigned int>(time(0)));

    //Declare Variable
    int computerNumber;
    int guessNumberTries;
    int guessNumber;

    //print Banner
    cout << "~~ This is a Casino Number Guessing Game ~~" <<endl <<endl;

    //Genreating random number 1-10 from pc
    computerNumber = rand()%11;

    //Get the number of times to get input
    cout << "Enter the number of times you want to Guess the Lucky number (Number between 1 - 10): ";
    cin >> guessNumberTries;

    for (int i = 0; i < guessNumberTries;i++)
    {
        //Program Logic
        cout << "You have " << (guessNumberTries - i) << " tries... Try to guess the number ";
        cout << "Enter the Lucky number to Win: " <<endl;
        cin >> guessNumber;

        //input validation
        if (guessNumber > 0 )

        if (guessNumber == computerNumber)
        {
            cout << "Dign Ding Ding..." << endl << "Correct Number Entered::" << endl << " Closing Program " <<endl << " -- Thank you for playing --" << endl;
            return 0;
        }
        else {
            cout << "Invalid Choice entered. Guess again; ";
        }

    }

    return 0;
}
